### ISSUE TITLE
[1기] 목표 🧭

### ISSUE THREAD

**Issue by beginin15** [back-stage/WeekBack#17]
1기동안 이루고 싶은 목표를 comment로 작성해주세요!

**Comment by beginin15** [comment]
## 1월
### 이력서용 프로젝트 완성 및 리팩토링
- [개인 프로젝트](https://github.com/beginin15/get-your-friday) 완성
- 코쿼 이슈 트래커 리팩토링

## 2월
### 이력서 작성
### 알고리즘

**Comment by suhyunsim** [comment]
## 1월
### 이력서용 프로젝트 완성
* [Photo Tag](https://github.com/SimLeeTag/photo-tag-backend) 완성

### 프로그래머스 스터디
* Facebook 클론 코딩

### 42 Seoul 프로젝트 제출
* Libft 과제

## 2월
### 이력서 작성

### 코딩 테스트 대비를 위한 알고리즘 문제 풀이

### 42 Seoul 프로젝트 제출
* ft_printf 과제

**Comment by hsik0225** [comment]
## 1월
### 독서
- 이펙티브 자바
- 클린 코드
- 엘레강트 오브젝트
## 2월
### 성실히 우테코 수강

**Comment by blossun** [comment]
## 1월
* [**스프링 기반 REST API 개발**](https://www.inflearn.com/course/spring_rest-api/dashboard) 강의 완강
* 프로그래머스 스터디 : Facebook클론서비스
* 42서울 과제 : netwhat

## 2월
* 이력서 제출
* 이슈트래커 리팩토링

**Comment by dev-Lena** [comment]
## 1월
### 이력서용 프로젝트 완성 및 리팩토링
* [photoTag](https://github.com/SimLeeTag/photo-tag-iOS) 완성

### 취준
* 경험 정리
* 깃허브 레포 정리
* CS 공부

## 2월
### iOS 공부
* SwiftUI + MVVM + Combine 공부

### 취준
* 알고리즘
* CS 공부
* 이력서 작성
* 포트폴리오 작성
