### ISSUE TITLE
[1기] 2월 취준 📑

### ISSUE THREAD

**Issue by beginin15** [back-stage/WeekBack#41]
# 개요
- 2월은 이력서와 관련된 구체적인 공동 목표는 없습니다.
- 각자 2월동안 이력서와 관련된 활동, 기술 면접 공부 등을 공유하고 싶으신 분은 이 이슈에 코멘트로 남겨주세요. 양식은 자유입니다.

**Comment by blossun** [comment]
* [그런 개발자로 괜찮은가 - '이력서'편](https://taetaetae.github.io/posts/a-good-developer-in-terms-of-resume/)

**Comment by dev-Lena** [comment]
[[인터뷰 후기] 사전과제로 75:1 경쟁률 뚫기](https://daheenallwhite.github.io/ios/interview/2020/07/16/Interview-Review/)

**Comment by dev-Lena** [comment]
### 6주차 약한 참조(weak reference) 목표

- [ ] 이력서 작성 - 1차
- [ ] 포트폴리오 - 1차
- [ ] 1곳 이상 지원
