### ISSUE TITLE
[2기] 3-4월 채용 소식

### ISSUE THREAD

**Issue by dev-Lena** [back-stage/WeekBack#72]
## 3-4월 채용 소식을 코멘트로 공유해주세요!  ◝(⁰▿⁰)◜ 

<br>

**으쌰 으쌰! (ง˙∇˙)ว  (ว˙∇˙)ง**

**Comment by beginin15** [comment]
|기관 및 주최|지원 링크|접수 기간|
|---|---|---|
|라인|[2021 신입 공채](https://careers.linecorp.com/ko/2021_1st)|2021.03.02 ~ 2021.03.15|
|프로그래머스|[2021 데브 매칭: 웹 백엔드(상반기)](https://programmers.co.kr/competitions/977?slug=2021-web-be-first&utm_campaign=competition977_introduce&utm_medium=banner&utm_source=programmers)|2021.03.08 ~ 2021.04.02 (시간 확인!)

**Comment by dev-Lena** [comment]
저도 여기에 업데이트하겠습니다!

|기관 및 주최|지원 링크|접수 기간|
|---|---|---|
|Wanted|[STARTUP Coding Festival](https://www.wanted.co.kr/events/scofe2021)|2021.03.17(신청) /  <br>2021.03.20(1차 대회) / <br>2021.03.27(2차 대회) /<br> 2021.04.03(시상식 & 채용 설명회)|
|카카오 뱅크|[2021 개발자 공개 채용](https://kakaobank.recruiter.co.kr/app/jobnotice/list)| ~2021.03.14|
|카카오 페이|[2021 경력 채용](https://kakaopay.recruiter.co.kr/app/jobnotice/list)|2021년 상시|
|왓챠|[멋진 동료를 구하고 있어요](https://watcha.team/fb9d1a3f-c79a-4430-8eb7-4e972027af2a)|상시 (날짜 확인!)|
|채널톡|[진행중인 채용](https://channel.io/ko/jobs)| 2021년 상시|
|포스타입|[엔지니어](https://about.postype.com/jobs)|상시 (날짜 확인!)|
|오늘의 집|[채용 중인 직무 - 개발](https://www.bucketplace.co.kr/recruit/?team=dev)|상시 (날짜 확인!)|
|Sendbird|[wanted - Sendbird](https://www.wanted.co.kr/company/88)| 상시 (날짜 확인!)|
|NHN|[기술 모집분야](https://recruit.nhn.com/ent/recruitings?type=class), [wanted - NHN](https://www.wanted.co.kr/company/13698)|상시 (날짜 확인!)|

제이의 템플릿 감사해용 🙏🏻

**Comment by blossun** [comment]
|기관 및 주최|지원 링크|접수 기간|
|---|---|---|
|프로그래머스|[2021 Dev-Matching: 웹 백엔드 개발자(상반기)](https://programmers.co.kr/competitions/977?slug=2021-web-be-first&utm_campaign=competition977_introduce&utm_medium=banner&utm_source=programmers)|04월 02일 17:00|
|프로그래머스|[2021 카카오커머스 개발자 공개채용](https://programmers.co.kr/competitions/1010?slug=2021-kakaocommerce-developers&utm_campaign=competition1010_introduce&utm_medium=banner&utm_source=programmers)|04월 02일 17:00|

**Comment by beginin15** [comment]
|기관 및 주최|지원 링크|접수 기간|
|---|---|---|
|프로그래머스|[2021 Summer Coding - 여름방학 스타트업 인턴 프로그램](https://programmers.co.kr/competitions/1043?slug=2021-summer-coding&utm_campaign=competition1043_introduce&utm_medium=banner&utm_source=programmers)|21년 04월 12일 11:00 ~ 05월 07일 17:00|
