### ISSUE TITLE
[2기] 3주차 주간 목표

### ISSUE THREAD

**Issue by beginin15** [back-stage/WeekBack#78]
## 목표 기한
03.15 ~ 03.21

## 최대 2가지 목표를 정해주세요.
**리더의 한마디**
저도 다른 분들처럼 원동력이 되는 한마디를 작성하고 싶어서 20분 넘게 고민했습니다. 이미 대실패 😿
대신 귀여운 토냥이 보고 가세요. 🐈

![KakaoTalk_Photo_2021-03-17-00-51-39](https://user-images.githubusercontent.com/33659848/111342337-b5162380-86bd-11eb-90af-cd47c9b0f7fd.jpeg)

**Comment by dev-Lena** [comment]
토냥이 보고 파워 업했습니당 감사해요 리더님 💜

**Comment by blossun** [comment]
사진에서 애정이 느껴지네요🥰
