### ISSUE TITLE
[2기] 4주차 주간 목표

### ISSUE THREAD

**Issue by blossun** [back-stage/WeekBack#84]
## 목표 기한
03.22 ~ 03.28

## 최대 2가지 목표를 정해주세요.
**리더의 한마디**
제가 좋아하는 꽃개🌼🐶 사진 총총
봄이 오려고 하네요 요즘 듣는 [이문세-봄바람](https://www.youtube.com/watch?v=smVvQVCtka4) bgm도 총총
다들 이번주도 화이팅
![586414948732181_20180323225040758](https://user-images.githubusercontent.com/35985636/111944948-17d34900-8b1c-11eb-98bf-640daee85930.JPG)

**Comment by dev-Lena** [comment]
뮤비 보고 왔습니다👀 이제 슬슬 봄바람🌸 부네요 뮤비 보니까 대청소 시즌🧹이 돌아왔다는걸 느꼈습니다 ㅎㅎㅎㅎ
꽃개🌼🐶 너무 귀엽네요 손도 가지런한것이 홍홍홍홍 다들 이번 한주도 화이팅입니다!
